# Generated by Django 4.2.27 on 2025-12-13 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10, unique=True)),
                ('superficie_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arrondissement',
                'verbose_name_plural': 'Arrondissements',
                'db_table': 'arrondissement',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('AIR', "Qualité de l'air"), ('TRAFIC', 'Trafic routier'), ('ENERGIE', 'Consommation énergétique'), ('DECHETS', 'Gestion des déchets'), ('ECLAIRAGE', 'Éclairage public')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='ACTIF', max_length=20)),
                ('date_installation', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capteurs', to='api.arrondissement')),
            ],
            options={
                'db_table': 'capteur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_unique', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('score_engagement', models.DecimalField(decimal_places=2, default=0, help_text='Score écologique (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('preference_mobilite', models.CharField(choices=[('VELO', 'Vélo'), ('TRANSPORT_COMMUN', 'Transport en commun'), ('COVOITURAGE', 'Covoiturage'), ('MARCHE', 'Marche'), ('VEHICULE_ELECTRIQUE', 'Véhicule électrique')], default='TRANSPORT_COMMUN', max_length=30)),
                ('notifications_actives', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'citoyen',
                'ordering': ['-score_engagement'],
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('MUNICIPALITE', 'Municipalité'), ('PRIVE', 'Partenaire Privé')], max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proprietaire',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('type_validation', models.CharField(choices=[('IA', 'Validation IA'), ('HUMAIN', 'Validation Humaine')], default='HUMAIN', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'technicien',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('BUS', 'Bus'), ('NAVETTE', 'Navette autonome'), ('UTILITAIRE', 'Véhicule utilitaire'), ('COLLECTE_DECHETS', 'Collecte des déchets')], max_length=20)),
                ('energie', models.CharField(choices=[('ELECTRIQUE', 'Électrique'), ('HYDROGENE', 'Hydrogène'), ('HYBRIDE', 'Hybride')], max_length=20)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('modele', models.CharField(blank=True, max_length=100, null=True)),
                ('annee_mise_service', models.IntegerField(blank=True, null=True)),
                ('capacite_passagers', models.IntegerField(blank=True, null=True)),
                ('autonomie_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('EN_SERVICE', 'En service'), ('MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='EN_SERVICE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicule',
                'ordering': ['plaque'],
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(max_length=255)),
                ('origine_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('origine_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('destination', models.CharField(max_length=255)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('depart', models.DateTimeField()),
                ('arrivee', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('economie_co2', models.DecimalField(blank=True, decimal_places=4, help_text='Économie CO2 en kg vs véhicule thermique', max_digits=10, null=True)),
                ('nombre_passagers', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajets', to='api.vehicule')),
            ],
            options={
                'db_table': 'trajet',
                'ordering': ['-depart'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('nature', models.CharField(choices=[('PREDICTIVE', 'Maintenance Prédictive'), ('CORRECTIVE', 'Maintenance Corrective'), ('CURATIVE', 'Maintenance Curative')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reduction_co2', models.DecimalField(blank=True, decimal_places=4, help_text='Réduction CO2 en kg', max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='api.capteur')),
                ('technicien_intervenant', models.ForeignKey(help_text="Technicien qui effectue l'intervention", on_delete=django.db.models.deletion.PROTECT, related_name='interventions_effectuees', to='api.technicien')),
                ('technicien_validateur', models.ForeignKey(help_text='Technicien qui valide (IA ou Humain)', on_delete=django.db.models.deletion.PROTECT, related_name='interventions_validees', to='api.technicien')),
            ],
            options={
                'db_table': 'intervention',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type_donnee', models.CharField(help_text='Type de donnée consultée', max_length=50)),
                ('zone_consultee', models.CharField(blank=True, max_length=100, null=True)),
                ('duree_consultation_secondes', models.IntegerField(blank=True, null=True)),
                ('source_consultation', models.CharField(choices=[('WEB', 'Application Web'), ('MOBILE', 'Application Mobile'), ('API', 'API')], default='WEB', max_length=10)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.citoyen')),
            ],
            options={
                'db_table': 'consultation',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='capteur',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capteurs', to='api.proprietaire'),
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('valeurs', models.JSONField(help_text='Valeurs des mesures selon le type de capteur')),
                ('indice_pollution', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('qualite_air', models.CharField(blank=True, choices=[('BON', 'Bon'), ('MODERE', 'Modéré'), ('MAUVAIS', 'Mauvais'), ('TRES_MAUVAIS', 'Très mauvais'), ('DANGEREUX', 'Dangereux')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='api.capteur')),
            ],
            options={
                'db_table': 'mesure',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['capteur', 'timestamp'], name='mesure_capteur_f532e1_idx'), models.Index(fields=['indice_pollution'], name='mesure_indice__a6f078_idx')],
            },
        ),
    ]
