# Generated by Django 4.2.27 on 2026-04-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('capteur', 'Capteur'), ('intervention', 'Intervention'), ('vehicule', 'Véhicule')], help_text="Type d'entité (capteur, intervention, vehicule)", max_length=20)),
                ('entity_id', models.CharField(help_text="ID de l'entité (UUID pour capteurs, int pour les autres)", max_length=50)),
                ('from_state', models.CharField(help_text='État avant la transition', max_length=30)),
                ('to_state', models.CharField(help_text='État après la transition', max_length=30)),
                ('event', models.CharField(help_text='Événement déclencheur', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date/heure de la transition')),
            ],
            options={
                'verbose_name': "Transition d'état",
                'verbose_name_plural': "Transitions d'état",
                'db_table': 'state_transitions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='state_trans_entity__5e8ca9_idx'), models.Index(fields=['timestamp'], name='state_trans_timesta_4994fc_idx')],
            },
        ),
    ]
