# Generated by Django 4.2.27 on 2026-04-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('air_quality', "Qualité de l'air"), ('interventions', 'Interventions de maintenance'), ('capteurs', 'État des capteurs')], help_text='Type de rapport', max_length=30)),
                ('content', models.TextField(help_text='Contenu du rapport généré')),
                ('date_range', models.CharField(blank=True, help_text='Date ou plage de dates du rapport', max_length=50, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Date/heure de génération')),
            ],
            options={
                'verbose_name': 'Rapport IA',
                'verbose_name_plural': 'Rapports IA',
                'db_table': 'ai_reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
